name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This is the new, updated build step
      - name: Build and push Add-on images
        uses: home-assistant/actions/addon-builder@master
        with:
          path: .
          test: false
          # The following docker-hub inputs are optional if you're only publishing to GHCR
          # They can be removed if you haven't set up Docker Hub secrets
          docker-hub-username: ${{ secrets.DOCKER_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}